export const themes: { [key: string]: string[] } = {
  space: [
    'galaxy', 'star', 'planet', 'asteroid', 'comet', 'nebula', 'black hole', 'supernova',
    'cosmos', 'universe', 'astronaut', 'spacecraft', 'orbit', 'gravity', 'lunar', 'solar',
    'celestial', 'constellation', 'meteor', 'cosmic', 'interstellar', 'alien', 'telescope',
    'quasar', 'pulsar', 'satellite', 'void', 'wormhole', 'light-year', 'parsec',
    'spacesuit', 'launch', 'thruster', 'trajectory', 'vacuum', 'starlight', 'singularity', 'ecliptic',
    'expedition', 'cosmonaut', 'extraterrestrial', 'orbiter', 'equinox', 'solstice', 'dark matter',
    'exoplanet', 'redshift', 'radiation', 'astrophysics', 'cosmology', 'spacetime', 'rover',
    'mission', 'payload', 'gravity well', 'stellar', 'libration', 'zodiac', 'apogee', 'perigee',
    'light cone', 'tidal', 'probe', 'flare', 'plasma', 'horizon', 'expansion', 'astronomy',
    'spectroscopy', 'observatory', 'magnification', 'lunar eclipse', 'solar eclipse', 'perseids',
    'andromeda', 'spiral galaxy', 'elliptical galaxy', 'irregular galaxy', 'black dwarf', 'white dwarf',
    'brown dwarf', 'neutron star', 'binary star', 'variable star', 'supergiant', 'hypernova',
    'suborbital', 'geostationary', 'interplanetary', 'extravehicular', 'payload bay', 'proton star',
    'solar wind', 'aurora', 'nova', 'dark energy', 'multiverse'
  ],
  food: [
    'Pizza', 'Burger', 'Pasta', 'Tacos', 'Sushi', 'Salad', 'Steak', 'Fries', 'Curry', 'Sandwich',
    'Dumplings', 'Paella', 'Ramen', 'Kebab', 'Fajitas', 'Lasagna', 'Biryani', 'Soup', 'Ice Cream',
    'Chocolate', 'Cheesecake', 'Brownie', 'Cupcake', 'Cookie', 'Donut', 'Bagel', 'Croissant',
    'Waffle', 'Pancake', 'Crepe', 'Muffin', 'Quiche', 'Pudding', 'Gelato', 'Sorbet', 'Churros',
    'Tiramisu', 'Macarons', 'Baklava', 'Pie', 'Granola', 'Toast', 'Cereal', 'Baguette',
    'Wrap', 'Spring Roll', 'Falafel', 'Caviar', 'Guacamole', 'Salsa', 'Hummus', 'Tapenade',
    'Bruschetta', 'Mozzarella Sticks', 'Nachos', 'Onion Rings', 'Popcorn', 'Trail Mix',
    'Yogurt', 'Smoothie', 'Milkshake', 'Cocktail', 'Tea', 'Coffee', 'Latte', 'Espresso',
    'Cappuccino', 'Mocha', 'Juice', 'Lemonade', 'Soda', 'Beer', 'Wine', 'Whiskey', 'Vodka',
    'Rum', 'Champagne', 'Gin', 'Brandy', 'Liquor', 'Martini', 'Margarita', 'Mocktail',
    'Hot Chocolate', 'Eggnog', 'Punch', 'Cider', 'Mead', 'Sake', 'Clam Chowder', 'Beef Stroganoff',
    'Risotto', 'Focaccia', 'Pita', 'Bagel Sandwich'
  ],
  fruits: [
    'Apple', 'Banana', 'Cherry', 'Date', 'Elderberry', 'Fig', 'Grape', 'Honeydew', 'Indian Fig',
    'Jackfruit', 'Kiwi', 'Lemon', 'Mango', 'Nectarine', 'Orange', 'Papaya', 'Quince', 'Raspberry',
    'Strawberry', 'Tomato', 'Ugli Fruit', 'Vanilla', 'Watermelon', 'Xigua', 'Yellow Passion Fruit',
    'Zucchini', 'Pineapple', 'Pomegranate', 'Blueberry', 'Cranberry', 'Blackberry', 'Gooseberry',
    'Lychee', 'Peach', 'Pear', 'Plum', 'Coconut', 'Cantaloupe', 'Apricot', 'Currant',
    'Persimmon', 'Dragonfruit', 'Durian', 'Rambutan', 'Sapodilla', 'Starfruit', 'Sugar Apple',
    'Custard Apple', 'Mulberry', 'Tamarind', 'Ackee', 'Soursop', 'Langsat', 'Longan',
    'Passionfruit', 'Breadfruit', 'Jabuticaba', 'Buddha’s Hand', 'Jujube', 'Salak', 'Chico',
    'Clementine', 'Tangerine', 'Mandarin', 'Kumquat', 'Mangosteen', 'Naranjilla', 'Pitaya',
    'Lucuma', 'Aronia', 'Sea Buckthorn', 'Camu Camu', 'Barberry', 'Maqui Berry', 'Goji Berry',
    'Goldenberry', 'Medlar', 'Rose Hip', 'Bilberry', 'Rowan', 'Cloudberry', 'Boysenberry',
    'Elderflower', 'Hawthorn Berry', 'Buffaloberry', 'Red Currant', 'White Currant', 'Huckleberry'
  ],
  flowers: [
    'Rose', 'Lily', 'Tulip', 'Orchid', 'Sunflower', 'Daisy', 'Marigold', 'Jasmine', 'Lotus',
    'Daffodil', 'Lavender', 'Chrysanthemum', 'Iris', 'Hibiscus', 'Poppy', 'Peony', 'Carnation',
    'Bougainvillea', 'Zinnia', 'Geranium', 'Hydrangea', 'Begonia', 'Violet', 'Anemone', 'Azalea',
    'Camellia', 'Dandelion', 'Freesia', 'Gardenia', 'Gladiolus', 'Honeysuckle', 'Lilac',
    'Magnolia', 'Mimosa', 'Nasturtium', 'Petunia', 'Primrose', 'Snapdragon', 'Tuberose',
    'Bleeding Heart', 'Baby’s Breath', 'Forget-Me-Not', 'Amaryllis', 'Buttercup', 'Heliotrope',
    'Larkspur', 'Morning Glory', 'Passionflower', 'Snowdrop', 'Bluebell', 'Foxglove', 'Pansy',
    'Phlox', 'Sweet Pea', 'Wisteria', 'Yarrow', 'Thistle', 'Marshmallow Flower', 'Canna',
    'Coreopsis', 'Cosmos', 'Lobelia', 'Delphinium', 'Hyacinth', 'Caladium', 'Snapdragon',
    'Bellflower', 'Aster', 'Edelweiss', 'Calendula', 'Crown Imperial', 'Scilla', 'Gerbera',
    'Allium', 'Zantedeschia', 'Cyclamen', 'Columbine', 'Japanese Camellia', 'Water Lily', 'Ivy'
  ],
  electronics: [
    'Smartphone', 'Laptop', 'Tablet', 'Smartwatch', 'Earbuds', 'Headphones', 'Camera', 'Drone',
    'TV', 'Speaker', 'Monitor', 'Keyboard', 'Mouse', 'Printer', 'Scanner', 'Hard Drive',
    'SSD', 'Router', 'Modem', 'Smart Home Hub', 'Thermostat', 'VR Headset', 'Gaming Console',
    'Projector', 'Power Bank', 'Charger', 'Memory Card', 'USB Drive', 'Graphics Card', 'Motherboard',
    'Processor', 'RAM', 'Cooling Fan', 'External Hard Drive', 'Bluetooth Speaker', 'Webcam',
    'Microwave', 'Refrigerator', 'Washing Machine', 'Dishwasher', 'Air Conditioner',
    'Electric Kettle', 'Toaster', 'Blender', 'Mixer', 'Oven', 'Vacuum Cleaner', 'Hair Dryer',
    'Electric Shaver', 'Water Purifier', 'Induction Stove', 'Slow Cooker', 'Rice Cooker',
    'Fitness Tracker', 'Home Theater', 'Soundbar', 'Digital Frame', 'Smart Lock',
    'Smart Doorbell', 'Wi-Fi Extender', 'Surge Protector', 'Portable Speaker',
    'Dash Cam', 'Car GPS', 'E-Reader', '3D Printer', 'Gaming Mouse', 'Mechanical Keyboard',
    'Smart Glasses', 'Wearable Camera', 'Noise-Canceling Headphones', 'Action Camera',
    'Electric Scooter', 'Robot Vacuum', 'Smart Plug', 'Smart Light Bulb', 'Smart Curtain Motor',
    'Temperature Sensor', 'Humidity Sensor', 'Air Purifier', 'Electric Blanket',
    'Dehumidifier', 'Humidifier', 'Smart Thermometer', 'Smart Scale', 'Barcode Scanner',
    'Digital Voice Recorder', 'Photo Printer', 'Label Printer', 'Document Scanner', 'Laser Printer'
  ],
  fish: [
    'Salmon', 'Tuna', 'Trout', 'Cod', 'Haddock', 'Mackerel', 'Sardine', 'Anchovy', 'Catfish',
    'Tilapia', 'Bass', 'Snapper', 'Grouper', 'Halibut', 'Swordfish', 'Shark', 'Eel', 'Flounder',
    'Herring', 'Pollock', 'Perch', 'Pike', 'Carp', 'Char', 'Barramundi', 'Bluefish', 'Crab',
    'Lobster', 'Shrimp', 'Prawn', 'Scallop', 'Clam', 'Mussel', 'Oyster', 'Octopus', 'Squid',
    'Sea Bass', 'Kingfish', 'Amberjack', 'Tilefish', 'Wahoo', 'Sablefish', 'Rockfish',
    'Skate', 'Mahi Mahi', 'Lingcod', 'Steelhead', 'Arctic Char', 'Yellowtail', 'Zander',
    'Redfish', 'Butterfish', 'Flying Fish', 'Milkfish', 'Rohu', 'Hilsa', 'Basa', 'Mudfish',
    'Snakehead', 'Silver Carp', 'Grass Carp', 'Bighead Carp', 'Flatfish', 'Pompano',
    'Monkfish', 'Hake', 'Sculpin', 'Sturgeon', 'Tilapia', 'Black Cod', 'Catla', 'Whiting',
    'Marlin', 'Bluefin Tuna', 'Skipjack', 'Albacore', 'Yellowfin', 'Bonito', 'Dogfish',
    'Sea Bream', 'Turbot', 'Sea Trout', 'Pink Salmon', 'Chinook Salmon', 'Coho Salmon',
    'Sockeye Salmon', 'Rainbow Trout', 'Brown Trout', 'Whitefish', 'Smelt', 'Ling', 'Blenny'
  ],
  goodComments: [
    'Great work!', 'Excellent job!', 'Well done!', 'Fantastic effort!', 'Amazing!', 'Superb!',
    'You nailed it!', 'Keep it up!', 'Brilliant!', 'Impressive!', 'Top-notch!', 'Outstanding!',
    'Remarkable!', 'Exceptional!', 'Marvelous!', 'Incredible!', 'Terrific!', 'Phenomenal!',
    'Spectacular!', 'Bravo!', 'Applause-worthy!', 'Magnificent!', 'Splendid!', 'Kudos!',
    'Good going!', 'You rock!', 'Hats off!', 'Much appreciated!', 'Nice work!', 'Thumbs up!',
    'Cheers!', 'Stellar performance!', 'You’re awesome!', 'Inspirational!', 'Outstanding!',
    'Gold standard!', 'Legendary!', 'Masterpiece!', 'Benchmark-worthy!', 'Effortless perfection!',
    'Exceptional dedication!', 'Terrific teamwork!', 'Inspirational leadership!', 'A true gem!',
    'Making a difference!', 'Consistent excellence!', 'Extraordinary focus!', 'Boundless creativity!',
    'Unwavering commitment!', 'Positive energy!', 'Unparalleled expertise!', 'Shining star!',
    'Impeccable precision!', 'A guiding light!', 'Model of professionalism!', 'Vivid imagination!',
    'Tenacious spirit!', 'Epic results!', 'Winning attitude!', 'Problem-solving hero!',
    'Valuable contributions!', 'Astonishing progress!', 'Dynamic collaboration!', 'Creative powerhouse!',
    'Unstoppable drive!', 'Ever-reliable!', 'Inspiring vision!', 'Loyal to excellence!', 'Brilliantly executed!',
    'Inspiring optimism!', 'Exceptionally skilled!', 'World-class performer!', 'Role model!',
    'True innovator!', 'Future-forward thinker!', 'Life-changing impact!', 'A leader’s leader!',
    'Consummate professional!', 'Team player!', 'Visionary thinker!', 'Master strategist!',
    'Pioneering spirit!', 'Creative genius!', 'Pillar of strength!', 'Relentless curiosity!',
    'A person of integrity!', 'Brightest mind!', 'Courageous explorer!', 'Changemaker!',
    'Diligent achiever!', 'Rock-solid performer!', 'A natural leader!', 'A builder of dreams!',
    'Relentless innovator!'
  ],
  countries: [
    'United States', 'Canada', 'Brazil', 'Argentina', 'Germany', 'France', 'Italy', 'Spain',
    'United Kingdom', 'Australia', 'Japan', 'China', 'India', 'Russia', 'South Africa',
    'Egypt', 'Kenya', 'Mexico', 'Colombia', 'Peru', 'Chile', 'Netherlands', 'Sweden',
    'Norway', 'Denmark', 'Finland', 'Iceland', 'Switzerland', 'Belgium', 'Poland',
    'Portugal', 'Greece', 'Turkey', 'Saudi Arabia', 'UAE', 'Israel', 'Iran', 'South Korea',
    'New Zealand', 'Indonesia', 'Thailand', 'Vietnam', 'Philippines', 'Malaysia',
    'Singapore', 'Bangladesh', 'Pakistan', 'Sri Lanka', 'Nepal', 'Bhutan', 'Myanmar',
    'Cambodia', 'Laos', 'Mongolia', 'Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iraq',
    'Syria', 'Lebanon', 'Jordan', 'Kuwait', 'Qatar', 'Bahrain', 'Oman', 'Yemen',
    'Sudan', 'Ethiopia', 'Nigeria', 'Ghana', 'Ivory Coast', 'Morocco', 'Tunisia',
    'Algeria', 'Libya', 'Angola', 'Zambia', 'Zimbabwe', 'Botswana', 'Namibia',
    'Mozambique', 'Madagascar', 'Mauritius', 'Seychelles', 'Maldives', 'Fiji',
    'Honduras', 'El Salvador', 'Panama', 'Costa Rica', 'Dominican Republic', 'Guatemala',
    'Haiti', 'Jamaica', 'Trinidad and Tobago', 'Barbados', 'Belize', 'Cuba', 'Guyana'
  ],
  currencies: [
    'Dollar', 'Euro', 'Pound', 'Yen', 'Rupee', 'Ruble', 'Won', 'Franc', 'Peso', 'Dinar',
    'Dirham', 'Ringgit', 'Rial', 'Taka', 'Shilling', 'Krona', 'Koruna', 'Lira', 'Baht',
    'Dong', 'Rand', 'Shekel', 'Leu', 'Zloty', 'Hryvnia', 'Kip', 'Kuna', 'Lev', 'Dram',
    'Manat', 'Tenge', 'Som', 'Afghani', 'Birr', 'Cedi', 'Naira', 'Pula', 'Kwanza',
    'Lilangeni', 'Nakfa', 'Ouguiya', 'Dalasi', 'Kwacha', 'Balboa', 'Bolivar', 'Guarani',
    'Peso Convertible', 'Colon', 'Cordoba', 'Quetzal', 'Lempira', 'Gourde', 'Surinamese Dollar',
    'Belize Dollar', 'East Caribbean Dollar', 'Cayman Islands Dollar', 'Jamaican Dollar',
    'Trinidad and Tobago Dollar', 'Bahamian Dollar', 'Barbadian Dollar', 'Aruban Florin',
    'Antillean Guilder', 'Cuban Peso', 'Honduran Lempira', 'El Salvador Colon', 'Dominican Peso',
    'Mexican Peso', 'Guatemalan Quetzal', 'Haitian Gourde', 'Argentine Peso', 'Chilean Peso',
    'Uruguayan Peso', 'Paraguayan Guarani', 'Brazilian Real', 'Colombian Peso', 'Peruvian Sol',
    'Venezuelan Bolivar', 'Panamanian Balboa', 'Costa Rican Colon', 'Nicaraguan Cordoba',
    'Salvadoran Colon', 'Bolivian Boliviano'
  ],
  colors: [
    'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Pink', 'Brown', 'Black', 'White',
    'Gray', 'Cyan', 'Magenta', 'Teal', 'Lavender', 'Beige', 'Coral', 'Maroon', 'Navy',
    'Olive', 'Turquoise', 'Silver', 'Gold', 'Bronze', 'Ivory', 'Charcoal', 'Peach',
    'Mint', 'Crimson', 'Amber', 'Lime', 'Emerald', 'Sapphire', 'Ruby', 'Topaz', 'Aquamarine',
    'Periwinkle', 'Indigo', 'Vermilion', 'Fuchsia', 'Mustard', 'Ochre', 'Slate', 'Azure',
    'Amethyst', 'Rose', 'Wine', 'Chocolate', 'Copper', 'Brass', 'Platinum', 'Steel', 'Obsidian',
    'Sand', 'Clay', 'Terracotta', 'Mahogany', 'Pine', 'Cedar', 'Spruce', 'Maple', 'Cherry',
    'Walnut', 'Ash', 'Birch', 'Fir', 'Bamboo', 'Ebony', 'Teak', 'Hickory', 'Palm', 'Oak',
    'Khaki', 'Alabaster', 'Jet', 'Olive Drab', 'Rust', 'Smoke', 'Peach Puff', 'Blush',
    'Lavender Mist', 'Goldenrod', 'Chartreuse', 'Carmine', 'Cerulean', 'Persimmon', 'Lilac',
    'Thistle', 'Mint Cream', 'Pale Violet', 'Forest Green', 'Ocean Blue', 'Seafoam'
  ],
  birds: [
    'Sparrow', 'Eagle', 'Hawk', 'Owl', 'Parrot', 'Penguin', 'Duck', 'Swan', 'Goose', 'Crow',
    'Pigeon', 'Woodpecker', 'Kingfisher', 'Flamingo', 'Peacock', 'Robin', 'Canary', 'Finch',
    'Magpie', 'Heron', 'Crane', 'Pelican', 'Albatross', 'Cormorant', 'Seagull', 'Tern',
    'Sandpiper', 'Stork', 'Kiwi', 'Toucan', 'Cockatoo', 'Falcon', 'Vulture', 'Macaw',
    'Lovebird', 'Jay', 'Raven', 'Swallow', 'Swift', 'Mockingbird', 'Lyrebird', 'Kookaburra',
    'Nightingale', 'Hummingbird', 'Dove', 'Bunting', 'Cardinal', 'Bluebird', 'Warbler',
    'Wren', 'Starling', 'Egret', 'Ibis', 'Kingbird', 'Lark', 'Quail', 'Parakeet',
    'Chickadee', 'Goldfinch', 'Harrier', 'Shrike', 'Osprey', 'Bittern', 'Snipe',
    'Hornbill', 'Weaver', 'Bowerbird', 'Cuckoo', 'Jacana', 'Avocet', 'Bee-eater',
    'Hoopoe', 'Barbet', 'Trogon', 'Motmot', 'Potoo', 'Booby', 'Petrel', 'Frigatebird',
    'Shearwater', 'Skua', 'Albatross', 'Darter', 'Grebe', 'Flufftail', 'Goshawk',
    'Honeyguide', 'Bushshrike', 'Thrush', 'Chat', 'Waxwing', 'Roller', 'Whimbrel'
  ]
};